### ISSUE TITLE
Do not wrap hidden fields within row view

### ISSUE THREAD

**Issue by widoz** [Chrico/wp-fields#11]
I noticed that hidden fields are treated like normal visible fields, so they are put within a table row when the form get rendered.

This has the disadvantage to introduce extra vertical space in the form where apparently there's nothing but the field exists, it's just hidden.

Wouldn't be ok to extract the hidden fields when the form is rendered and move them as direct childs of the form markup instead of within a table row?

**Comment by Chrico** [comment]
"Fixed" in version 2.0.0 which adds a CSS class "hidden" to the form row. 👀
