### ISSUE TITLE
Wrong method names in documentation

### ISSUE THREAD

**Issue by XedinUnknown** [Chrico/wp-fields#6]
## The Problem
In many cases, the documentation mentions method names that are incorrect.

## Possible Cause
At first, the library was written using WP code standards, and the names used to be e.g. `set_field()`. Later, the library got re-factored to use a more modern standard, where the names are e.g. `withField()`; but the documentation was not updated.

## Suggested Solution
Update the documentation to reflect the new names.

**Comment by Chrico** [comment]
Thanks for your feedback. Where have you seen those? I cannot find `set_field` nor `withField` (maybe you mean `withElement` in https://github.com/Chrico/wp-fields/blob/master/docs/02%20-%20create%20forms.md ?

The API has changed with version 1.0, where the documention was also updated (e.G. https://github.com/Chrico/wp-fields/commit/5328bc6648d90d06f00cfd5e4f329661a90776b8#diff-01c29b9da7f913b5e9470012c0971cca ) according due those changes. Maybe you look at the documentation <1.0 ?

**Comment by XedinUnknown** [comment]
Yep, `set_field()` is just an example, using `field` as placeholder. In the documentation, there's `add_filter()` -> `withFilter()`, `add_validator()` -> `withValidator()`. That's what I saw, but maybe there are more.

**Comment by Chrico** [comment]
updated some position. seems it was in text some old names.

**Comment by XedinUnknown** [comment]
LGTM
